### ISSUE TITLE
Crash noted when attempting to search while automatically opening > 30 tabs.

### ISSUE THREAD

**Issue by bartola** [inactivist/chrome-qfind#10]
1 launch chrome browser on OSX 10.9
2 right click on a link folder (with 31 link)
3 select open all bookmarks in new window
4 click on qfind "search term= BMW"
5 click on tabs that finished loading

Result: After a brief wait the browser closed, all tabs closed.

NOTE: I was not able to reproduce the issue and I did not monitor resource usage.

**Comment by inactivist** [comment]
Did you enter a search term?  Or was the search box left blank?

**Comment by bartola** [comment]
Yes, updated the steps. However, I must have had an IDE open or VM. I opened > 41 tabs enter the term and it worked great. You can close this issue.

![2013-11-13_2200](https://f.cloud.github.com/assets/2125649/1538713/36f4c0e0-4cf2-11e3-8d76-160e57a761be.png)

**Comment by inactivist** [comment]
Thanks for the update.  Let me know if it happens again, and I'll re-open this one.  I can't think of any reason it'd crash Chrome, but you never know...

**Comment by inactivist** [comment]
[OT] Interesting, it appears there's a visual glitch on Mac -- based on your attached screen capture -- the result selection checkbox should be centered in the left column as is the case with the icon and the close [X] button.  

I don't have a Mac available for testing... sigh.
